export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const USE_RIGHT_CHAT_PANEL = 'USE_RIGHT_CHAT_PANEL';
export const CHANGE_AUTHORIZATION = 'CHANGE_AUTHORIZATION';